version: '2'
services:
    smart_newsletter-app:
        image: smart_newsletter
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://smart_newsletter-postgresql:5432/smart_newsletter
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smart_newsletter-postgresql:
        extends:
            file: postgresql.yml
            service: smart_newsletter-postgresql
